name: fish # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '3.5.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Friendly interactive shell # 79 char long summary
description: |
 Fish is a shell geared towards interactive use.  Its features are focused on
 user friendliness and discoverability.  The language syntax is simple but
 incompatible with other shell languages.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

build-packages:
  - ncurses-dev
  - libncurses5-dev
  - libpcre2-dev
  - gettext
parts:
  fish:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/fish-shell/fish-shell/releases/download/3.5.1/fish-3.5.1.tar.xz

apps:
  fish:
    command: usr/local/bin/fish
